export const DISCORD_CONFIG = {
  DISCORD_PUBLIC_KEY: process.env.DISCORD_PUBLIC_KEY!,
  DISCORD_APPLICATION_ID: process.env.DISCORD_APPLICATION_ID!,
  DISCORD_BOT_TOKEN: process.env.DISCORD_BOT_TOKEN!,
  DISCORD_API_BASE_URL: 'https://discord.com/api/v10',
}
